document.writeln("<div class=\'nav-bar\'>");
document.writeln("        <div class=\'inner-content w\'>");
document.writeln("            <div class=\'l-nav\'>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <a href=\'http: //jx3.xoyo.com/\'>");
document.writeln("                        <img src=\'./assets/images/logo-small.png\' alt=\'剑网3\'>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'slogan\'></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'r-nav\'>");
document.writeln("                <div class=\'t-links\'>");
document.writeln("                    <a class=\'hlight link login\' class=\'btn btn-primary btn-lg\' data-toggle=\'modal\'");
document.writeln("                        data-target=\'#myModal\'>登录</a>");
document.writeln("                    <a class=\'hlight link login\' class=\'btn btn-primary btn-lg\' data-toggle=\'modal\'");
document.writeln("                        data-target=\'#myModal\'>注册</a>");
document.writeln("                    <a href=\'https://charge.xoyo.com\' class=\'hlight link\'>充值</a>");
document.writeln("                    <a href=\'player.html\' class=\'hlight link\'>老玩家回归指南</a>");
document.writeln("                    <a href=\'https://kefu.xoyo.com\' class=\'link\'>客服</a>");
document.writeln("                    <a href=\'https://passport.xoyo.com\' class=\'link\'>增值服务</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");