document.writeln("<div class=\'footer\'>");
document.writeln("        <div class=\'w\'>");
document.writeln("            <p class=\'footer-top clearfix\'>");
document.writeln("                <span class=\'fl\'>");
document.writeln("                    <a href=\'javascript:;\'>");
document.writeln("                        <img src=\'./assets/images/jinshan.png\' alt=\'金山软件\'>");
document.writeln("                    </a>");
document.writeln("                    <a href=\'javascript:;\'>");
document.writeln("                        <img src=\'./assets/images/xishanju.png\' alt=\'金山软件\'>");
document.writeln("                    </a>");
document.writeln("                </span>");
document.writeln("                <span class=\'fl link\'>");
document.writeln("                    <a href=\'javascript:;\'>关于我们</a> |");
document.writeln("                    <a href=\'javascript:;\'>服务协议</a> |");
document.writeln("                    <a href=\'javascript:;\'>客户中心</a> |");
document.writeln("                    <a href=\'javascript:;\'>联系我们</a> |");
document.writeln("                    <a href=\'javascript:;\'>诚聘英才</a>");
document.writeln("                </span>");
document.writeln("            </p>");
document.writeln("            <p class=\'footer-mid\'>");
document.writeln("                <span class=\'public_footer_mid_font\'");
document.writeln("                    style=\'transform: scale(0.8); display: block; transform-origin: left\'>Copyright © 1999-");
document.writeln("                    <span class=\'J_pubFootYear\'>2019</span>");
document.writeln("                    <span class=\'J_pubFootCompany\'>成都西山居世游科技有限公司</span>");
document.writeln("                    版权所有");
document.writeln("                </span>");
document.writeln("            </p>");
document.writeln("            <p class=\'footer-mid\'>");
document.writeln("                <span style=\'transform: scale(0.8); display: block; transform-origin: left\'>增值电信业务经营许可证 川B2-20130104");
document.writeln("                    蜀ICP备14009198号-2 川公网安备51019002000850号 文网游备字〔2017〕Ｃ-RPG 0031 号</span>");
document.writeln("            </p>");
document.writeln("            <p class=\'footer-mid\'>");
document.writeln("                <span class=\'public_footer_mid_font\'");
document.writeln("                    style=\'transform: scale(0.8); display: block; transform-origin: left\'><a");
document.writeln("                        href=\'https://help.xoyo.com/agreement?name=network-culture-operation-license\' target=\'_blank\'");
document.writeln("                        title=\'网络文化经营许可证 川网文[2018]9435-346号\'");
document.writeln("                        style=\'color: #555; padding: 0 2px; text-decoration: none\'>网络文化经营许可证 川网文[2018]9435-346号</a>　<a");
document.writeln("                        href=\'https://help.xoyo.com/agreement?name=internet-publishing-license\'");
document.writeln("                        style=\'color: #555; padding: 0 2px; text-decoration: none\'>互联网出版许可证");
document.writeln("                        新出网证&lt;川&gt;字027号</a></span>");
document.writeln("            </p>");
document.writeln("            <p class=\'footer-mid\'>");
document.writeln("                <span class=\'public_footer_mid_font\'");
document.writeln("                    style=\'transform: scale(0.8); display: block; transform-origin: left\'><a");
document.writeln("                        href=\'https://help.xoyo.com/agreement?name=information-system-security-level-protection-certificate\'");
document.writeln("                        target=\'_blank\' title=\'信息系统安全等级保护备案证书编号：51010013010\'");
document.writeln("                        style=\'color: #555; padding: 0 2px; text-decoration: none\'>信息系统安全等级保护备案证书编号：51010013010</a>　<a");
document.writeln("                        href=\'https://help.xoyo.com/agreement?name=network-game-management\' target=\'_blank\'");
document.writeln("                        style=\'color: #555; padding: 0 2px; text-decoration: none\'>《网络游戏管理暂行办法》第九条内容</a> <a");
document.writeln("                        href=\'https://help.xoyo.com/agreement?name=china-cybersecurity-law\' target=\'_blank\'");
document.writeln("                        style=\'color: #555; padding: 0 2px; text-decoration: none\'>《中华人民共和国网络安全法》</a></span>");
document.writeln("            </p>");
document.writeln("            <p class=\'footer-bottom\'>");
document.writeln("                <span class=\'fl\'>");
document.writeln("                    <a href=\'javascript:;\'>");
document.writeln("                        <img src=\'./assets/images/wj.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <a href=\'javascript:;\'>");
document.writeln("                        <img src=\'./assets/images/wj2.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                </span>");
document.writeln("                <span class=\'fl\'>");
document.writeln("                    <span class=\'public_footer_mid_font\'");
document.writeln("                        style=\'transform: scale(0.8); display: block; transform-origin: left\'>婉拒18岁以下未成年用户进入游戏");
document.writeln("                        健康游戏忠告：抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身<br>合理安排时间 享受健康生活 进入：<a");
document.writeln("                            href=\'https://kefu.xoyo.com/index.php?r=article&amp;id=63\' target=\'_blank\'");
document.writeln("                            style=\'color: #555; padding: 0 2px; text-decoration: none\'>未成年人家长监护系统</a> <a target=\'_blank\'");
document.writeln("                            href=\'http://report.12377.cn:13225/toreportinputNormal_anis.do\'");
document.writeln("                            style=\'color: #cc0e2b; padding: 0 2px; text-decoration: none\'>违法和不良信息举报中心</a></span>");
document.writeln("                </span>");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");