document.writeln("<div class=\'modal\' id=\'myModal\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("    <div class=\'modal-dialog modal-lg\'>");
document.writeln("        <!-- 内容 -->");
document.writeln("        <div class=\'modal-content modal-con\'>");
document.writeln("            <!-- 头部 -->");
document.writeln("            <div class=\'modal-header\'>");
document.writeln("                <button type=\'button\' class=\'close close-btn\' data-dismiss=\'modal\' aria-hidden=\'true\'></button>");
document.writeln("            </div>");
document.writeln("            <!-- 主体 -->");
document.writeln("            <div class=\'modal-body\'>");
document.writeln("                <!-- 左侧信息区 -->");
document.writeln("                <div class=\'l-info-box\'>");
document.writeln("                    <div class=\'register\'>");
document.writeln("                        <ul class=\'clearfix\'>");
document.writeln("                            <li class=\'fl tab_con tab_con_left active\'>");
document.writeln("                                <span class=\'register-arrow\'></span>");
document.writeln("                                手机注册");
document.writeln("                            </li>");
document.writeln("                            <li class=\'fl tab_con tab_con_right\'>");
document.writeln("                                <span class=\'register-arrow\'></span>");
document.writeln("                                普通注册");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <!-- 表单切换区域 -->");
document.writeln("                    <div id=\'tab_content\'>");
document.writeln("                        <!-- 左侧表单(手机注册) -->");
document.writeln("                        <div class=\'tab_content_left tab\'>");
document.writeln("                            <div class=\'form-group\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp tel\' type=\'text\' placeholder=\'输入手机号\'>");
document.writeln("                                <span class=\'error-icon\'></span>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>手机号不能为空</label>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group id_code_box\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp code\' type=\'text\' placeholder=\'短信验证码\'>");
document.writeln("                                <span class=\'error-icon code-error-icon\'></span>");
document.writeln("                                <div class=\'id_code\'>");
document.writeln("                                    发送验证码");
document.writeln("                                </div>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>验证码不能为空</label>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group eye_box has-feedback\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp pwd\' type=\'password\'");
document.writeln("                                    placeholder=\'密码(8-32位字母/数字/符号组合)\'>");
document.writeln("                                <span class=\'error-icon pwd-error-icon\'></span>");
document.writeln("                                <div class=\'eye\'></div>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>8-32位，需要字母/数字/符号其中2种或以上</label>");
document.writeln("                            </div>");
document.writeln("                            <input type=\'checkbox\' value=\'\' class=\'ck\' checked=\'checked\'>");
document.writeln("                            <span class=\'deal\'>我同意金山网络服务使用协议</span>");
document.writeln("                            <button type=\'button\' class=\'btn btn-default btn-lg btn-block submit submit1\'>确定</button>");
document.writeln("                        </div>");
document.writeln("                        <!-- 右侧表单(普通注册) -->");
document.writeln("                        <div class=\'tab_content_right tab\'>");
document.writeln("                            <div class=\'form-group\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp user\' type=\'text\'");
document.writeln("                                    placeholder=\'输入账号(首位字母,非邮箱,4-18位)\'>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>用户名不能为空</label>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group eye_box\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp pwd\' type=\'password\'");
document.writeln("                                    placeholder=\'密码(8-32位字母/数字/符号组合)\'>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>密码不能为空（8-32位，需要字母/数字/符号其中2种或以上）</label>");
document.writeln("                                <div class=\'eye\'></div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp tel\' type=\'text\' placeholder=\'输入手机号\'>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>手机号不能为空</label>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group id_code_box\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp code\' type=\'text\' placeholder=\'短信验证码\'>");
document.writeln("                                <div class=\'id_code\'>");
document.writeln("                                    发送验证码");
document.writeln("                                </div>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>验证码不能为空</label>");
document.writeln("                            </div>");
document.writeln("                            <p class=\'policy\'>根据国家规定请填写真实身份信息，官方会依法保护您的隐私: </p>");
document.writeln("                            <div class=\'form-group bottom\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp real_name\' type=\'text\' placeholder=\'输入真实姓名\'>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>输入真实姓名</label>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'form-group bottom\'>");
document.writeln("                                <input class=\'form-control input-lg con_inp id_card\' type=\'text\' placeholder=\'输入身份证号码\'>");
document.writeln("                                <label class=\'control-label\' for=\'inputSuccess2\'>输入身份证号码</label>");
document.writeln("                            </div>");
document.writeln("                            <input type=\'checkbox\' value=\'\' class=\'ck\' checked=\'checked\'>");
document.writeln("                            <span class=\'deal\'>我同意金山网络服务使用协议</span>");
document.writeln("                            <button type=\'button\' class=\'btn btn-default btn-lg btn-block submit submit2\'>确定</button>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <!-- 右侧轮播区 -->");
document.writeln("                <div class=\'r-tabside-box\'>");
document.writeln("                    <div class=\'right_slides\'>");
document.writeln("                        <div class=\'right_slides_item\'>");
document.writeln("                            <img src=\'./assets/images/modal/s-rig01.jpg\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'right_slides_item\'>");
document.writeln("                            <img src=\'./assets/images/modal/s-rig02.jpg\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'right_slides_item\'>");
document.writeln("                            <img src=\'./assets/images/modal/s-rig03.jpg\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'right_slides_item\'>");
document.writeln("                            <img src=\'./assets/images/modal/s-rig04.jpg\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");